language: go

go:
  - 1.6.3
  - tip

#Importing of external libs
go_import_path:

# Whitelisting branches
branches:
  only:
    - master

# Prepare Python environment
before_install:
  - sudo pip install --upgrade pip
  - sudo pip install requests --upgrade

# Install external libs and Coveralls to check coverage
install:
  - go get github.com/calbucci/go-htmlparser
  - go get github.com/goinggo/tracelog
  - go get github.com/nu7hatch/gouuid
  - go get golang.org/x/net/context
  - go get golang.org/x/oauth2
  - go get golang.org/x/oauth2/google
  - go get google.golang.org/api/gmail/v1

  - sudo pip install coveralls

script:
  - make test

# Run Coveralls after build
after_success:
  -coveralls

notifications:
  email:
    on_success: change
    on_failure: always
  
