language: go

go:
  - 1.6.3
  - tip

# Whitelisting
branches:
  only:
    - master
before_install:
  - sudo pip install --upgrade pip
  - sudo pip install requests --upgrade

install:
  - sudo pip install coveralls

after_success:
  -coveralls